// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ChangeLanguageVersionExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidChangeLanguageVersionCommandPackageString = "7539965f-1675-4b78-a8c1-648e4de69be4";
        public const string guidChangeLanguageVersionCommandPackageCmdSetString = "d09ad2ce-4234-462e-a4d4-9ce671cdd420";
        public static Guid guidChangeLanguageVersionCommandPackage = new Guid(guidChangeLanguageVersionCommandPackageString);
        public static Guid guidChangeLanguageVersionCommandPackageCmdSet = new Guid(guidChangeLanguageVersionCommandPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int IDG_VS_CTXT_PROJECT_SETLANGVER = 0x1020;
        public const int IDG_VS_CTXT_PROJECT_SETLANGVER_OPTIONS = 0x1028;
        public const int IDM_VS_CSCD_PROJECT_SETLANGVER = 0x0100;
        public const int cmdSetToDefault = 0x0F00;
        public const int cmdSetToLatest = 0x0F01;
        public const int cmdSetToCSharp5 = 0x0F02;
        public const int cmdSetToCSharp6 = 0x0F03;
        public const int cmdSetToCSharp7 = 0x0F04;
        public const int cmdSetToCSharp71 = 0x0F05;
        public const int cmdSetToCSharp72 = 0x0F06;
        public const int cmdSetToCSharp73 = 0x0F07;
    }
}
